version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: "daily"
    time: "03:00"
    timezone: "Europe/London"
  target-branch: "9.x"
  open-pull-requests-limit: 10
